//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InThuDoEntities : DbContext
    {
        public InThuDoEntities()
            : base("name=InThuDoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<EmployeeDepartmentMapping> EmployeeDepartmentMappings { get; set; }
        public DbSet<LibDepartment> LibDepartments { get; set; }
        public DbSet<LibDepositType> LibDepositTypes { get; set; }
        public DbSet<LibOrderStatu> LibOrderStatus { get; set; }
        public DbSet<LibRoleType> LibRoleTypes { get; set; }
        public DbSet<LibShippingMethod> LibShippingMethods { get; set; }
        public DbSet<LocaleStringResource> LocaleStringResources { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<OrderStatusMapping> OrderStatusMappings { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<DesignRequest> DesignRequests { get; set; }
        public DbSet<ManufactureRequest> ManufactureRequests { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<UserOrganizationMappping> UserOrganizationMapppings { get; set; }
        public DbSet<LibCustomerType> LibCustomerTypes { get; set; }
        public DbSet<LibPrintingType> LibPrintingTypes { get; set; }
    }
}
