//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibDepartment
    {
        public LibDepartment()
        {
            this.EmployeeDepartmentMappings = new HashSet<EmployeeDepartmentMapping>();
        }
    
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EmployeeDepartmentMapping> EmployeeDepartmentMappings { get; set; }
    }
}
