//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufactureRequest
    {
        public int ManufactureRequestId { get; set; }
        public int DesignRequestId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> CustomerApproved { get; set; }
        public Nullable<System.DateTime> CustomerApprovedDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> CustomerApprovedQuantity { get; set; }
        public Nullable<decimal> CustomerApprovedPrice { get; set; }
        public Nullable<bool> IsFailed { get; set; }
        public int ManufactureId { get; set; }
    
        public virtual DesignRequest DesignRequest { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
