//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderStatusMappings = new HashSet<OrderStatusMapping>();
        }
    
        public int OrderId { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> DepositTypeId { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> ExpectedCompleteDate { get; set; }
        public string Note { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<bool> ApprovedByCustomer { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LibDepositType LibDepositType { get; set; }
        public virtual LibShippingMethod LibShippingMethod { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderStatusMapping> OrderStatusMappings { get; set; }
    }
}
