//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderStatusMappings = new HashSet<OrderStatusMapping>();
            this.DesignRequests = new HashSet<DesignRequest>();
        }
    
        public int OrderItemId { get; set; }
        public int ProductId { get; set; }
        public string Specification { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> DesignerId { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<bool> CustomerApproved { get; set; }
        public Nullable<System.DateTime> CustomerApprovedDate { get; set; }
        public string Note { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual OrderItem OrderItem1 { get; set; }
        public virtual OrderItem OrderItem2 { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<OrderStatusMapping> OrderStatusMappings { get; set; }
        public virtual ICollection<DesignRequest> DesignRequests { get; set; }
    }
}
