//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Designs = new HashSet<Design>();
            this.Designs1 = new HashSet<Design>();
            this.Designs2 = new HashSet<Design>();
            this.EmployeeDepartmentMappings = new HashSet<EmployeeDepartmentMapping>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.Orders2 = new HashSet<Order>();
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderItems1 = new HashSet<OrderItem>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<bool> Deteted { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Customer> Customers1 { get; set; }
        public virtual ICollection<Design> Designs { get; set; }
        public virtual ICollection<Design> Designs1 { get; set; }
        public virtual ICollection<Design> Designs2 { get; set; }
        public virtual ICollection<EmployeeDepartmentMapping> EmployeeDepartmentMappings { get; set; }
        public virtual LibRoleType LibRoleType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<Order> Orders2 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<OrderItem> OrderItems1 { get; set; }
    }
}
